### ISSUE TITLE
selectedItem from unfiltered list returns "undefined"

### ISSUE THREAD

**Issue by virtualbjorn** [davecoffin/nativescript-filterable-listpicker#24] opened 2018-05-29 12:27 UTC
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- not Tried on iOS but it persis on Android
- 4.0.1
- Android Device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.0.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): 
- "@angular/animations": "~4.2.0",
-   "@angular/common": "~4.2.0",
-     "@angular/compiler": "~4.2.0",
-     "@angular/core": "~4.2.0",
-     "@angular/forms": "~4.2.0",
-     "@angular/http": "~4.2.0",
-     "@angular/platform-browser": "~4.2.0",
-     "@angular/router": "~4.2.0",
-     "nativescript-angular": "~4.2.0",
-     "nativescript-filter-select": "^1.1.1",
-     "nativescript-filterable-listpicker": "^2.0.2",
-     "nativescript-theme-core": "~1.0.2",
-     "reflect-metadata": "~0.1.8",
-     "rxjs": "~5.4.2",
-     "tns-core-modules": "~3.1.0",
-     "zone.js": "~0.8.2"

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

- Select an item from unfiltered list.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by virtualbjorn** [comment] 2018-05-29 12:32
I found a fix for it we just have to declare the 
        _this.source = unfilteredSource;
before
textfield.on('textChange', function (data)

**Comment by virtualbjorn** [comment] 2018-05-29 12:37
```Typescript
        innerComponent.bindingContext = this;
        this.addChild(innerComponent);
        let textfield: TextField = <TextField>innerComponent.getViewById('filterTextField');
        this.source = unfilteredSource;    //THIS LINE HERE IS TO BE ADDED
        textfield.on('textChange', (data: any) => {
            filtering = true;
            this.source = unfilteredSource.filter(item => {
                if (item.title) {
                    return item.title.toLowerCase().indexOf(data.value.toLowerCase()) !== -1;
                } else {
                    return item.toLowerCase().indexOf(data.value.toLowerCase()) !== -1;
                }
                
            })
            filtering = false;
        })
```

**Comment by virtualbjorn** [comment] 2018-05-29 12:40
I know how to fix it. I'm gonna do a pull request to the repo.

**Comment by virtualbjorn** [comment] 2018-05-29 12:50
@davecoffin I can't push my contribution to your repo since I'm not one a collaborator yet.

**Comment by davecoffin** [comment] 2018-05-30 12:04
Create a fork of the repo and submit a pull request so I can review.

Why are your core modules still on 3.x? `"tns-core-modules": "~3.1.0",`
That could be your problem if your runtimes and cli version are on 4.x, you need to update your core modules.

**Comment by virtualbjorn** [comment] 2018-05-30 14:23
I tried it on newer template still the same error, but I found a work around though. Just need to try it out.

**Comment by virtualbjorn** [comment] 2018-05-31 05:29
I tried running the demo app but to no avail. So I created a new angular template then added the plugin.
Successfully implemented the demo but in first instance of the listpicker when you haven't filtered it yet and selected an item, for example you directly tapped the unfiltered list item and it returns undefined on alert.

**Comment by davecoffin** [comment] 2018-07-13 12:58
I'm closing this because I can't reproduce it. Try the latest version, 2.1.0.

**Closed by davecoffin** 2018-07-13 12:58 UTC
